###############################################################################
# 09_figures.R
#
# Generate all manuscript figures and Table 1.
#
# Figures produced (PNG):
#
#   Main figures:
#   fig1a_forest_glp1r.png      — Fig 1a: GLP1R forest plot (response ratio + embedded table)
#   fig1b_forest_gipr.png       — Fig 1b: GIPR forest plot (response ratio + embedded table)
#   fig1c_drug_comparison.png   — Fig 1c: GLP1R violin/box plots by drug (carriers vs controls)
#   fig1d_slopegraph_glp1r.png  — Fig 1d: GLP1R individual carrier slopegraph by drug
#
#   Supplementary figures:
#   supp_fig_gipr_violin.png     — GIPR violin/box plots (sema + tirz; mirrors Fig 1c for GIPR)
#   supp_fig_gipr_slopegraph.png — GIPR individual carrier slopegraph (mirrors Fig 1d for GIPR)
#   ed_fig_subgroup_glp1r.png   — GLP1R variant class subgroups + treatment-naive (forest)
#   ed_fig_subgroup_gipr.png    — GIPR variant class subgroups (forest)
#   ed_fig_regenie.png          — Regenie burden test sensitivity results
#   ed_fig_aou.png              — All of Us replication
#
#   Tables:
#   table1_glp1r.csv                              — GLP1R baseline characteristics (pre/post-match with SMD)
#   table1_gipr.csv                               — GIPR baseline characteristics (pre/post-match with SMD)
#   supplementary_table_glp1r_variants.tsv        — GLP1R primary carriers: one row per variant
#   supplementary_table_gipr_variants.tsv         — GIPR primary carriers: one row per variant
#
# Note on study design schematic: prepared separately as an illustration;
# not generated by this script.
#
# Colour palette: defined in config.R (COLORS list)
#
# Paper: "Rare GLP1R variants selectively attenuate weight loss with
#         semaglutide versus tirzepatide"
###############################################################################

library(tidyverse)
library(patchwork)

source("config.R")

fig_dir <- file.path(PATHS$output_dir, "figures")
dir.create(fig_dir, showWarnings = FALSE)


###############################################################################
# SHARED THEME
###############################################################################

# Font family used throughout. "sans" is cross-platform (Helvetica on macOS/Linux,
# Arial on Windows). To use Arial specifically, install the extrafont package and
# call extrafont::loadfonts() before running this script, then change FONT_FAMILY
# below to "Arial".
FONT_FAMILY <- "sans"

theme_paper <- function(base_size = 10) {
  theme_minimal(base_size = base_size) +
    theme(
      text             = element_text(size = base_size, family = FONT_FAMILY),
      axis.text        = element_text(size = base_size - 1, colour = "black"),
      axis.title       = element_text(size = base_size, face = "bold"),
      plot.title       = element_text(size = base_size + 1, face = "bold"),
      plot.subtitle    = element_text(size = base_size - 1),
      legend.text      = element_text(size = base_size - 1),
      legend.title     = element_text(size = base_size - 1, face = "bold"),
      legend.key.size  = unit(4, "mm"),
      panel.grid.minor = element_blank(),
      panel.grid.major = element_line(colour = "grey90", linewidth = 0.3),
      panel.border     = element_rect(fill = NA, colour = "black", linewidth = 0.5),
      strip.text       = element_text(size = base_size - 1, face = "bold"),
      strip.background = element_blank(),
      plot.margin      = margin(10, 10, 10, 10)
    )
}

save_fig <- function(plot, name, width = 9.71, height = 5.1, dpi = 300) {
  ggsave(file.path(fig_dir, paste0(name, ".png")),
         plot, width = width, height = height, units = "in", dpi = dpi)
  cat(sprintf("Saved: %s.png\n", name))
}


###############################################################################
# LOAD RESULTS
###############################################################################

results_primary     <- readRDS(file.path(PATHS$output_dir, "results_primary.rds"))
results_interaction <- readRDS(file.path(PATHS$output_dir, "results_interaction.rds"))
results_subgroup    <- readRDS(file.path(PATHS$output_dir, "results_subgroup.rds"))
balance_summary     <- readRDS(file.path(PATHS$output_dir, "balance_summary.rds"))
results_regenie     <- tryCatch(
  readRDS(file.path(PATHS$output_dir, "results_regenie.rds")),
  error = function(e) { cat("Regenie results not found; skipping regenie figure.\n"); NULL }
)

matched_glp1r_overall   <- readRDS(file.path(PATHS$output_dir, "matched_glp1r_overall.rds"))
matched_glp1r_tirzepatide <- readRDS(file.path(PATHS$output_dir, "matched_glp1r_tirzepatide.rds"))
matched_gipr_overall    <- readRDS(file.path(PATHS$output_dir, "matched_gipr_overall.rds"))
matched_gipr_tirzepatide  <- readRDS(file.path(PATHS$output_dir, "matched_gipr_tirzepatide.rds"))

# For violin and slopegraph figures, the tirzepatide panel must match the
# tirzepatide-specific forest plot row (which uses matched_*_tirzepatide, not
# the overall matched data filtered to drug=="tirzepatide").
# Build combined viz datasets: sema rows from overall, tirz rows from tirz-specific.
matched_glp1r <- bind_rows(
  matched_glp1r_overall     %>% filter(drug == "semaglutide"),
  matched_glp1r_tirzepatide
)
matched_gipr <- bind_rows(
  matched_gipr_overall     %>% filter(drug == "semaglutide"),
  matched_gipr_tirzepatide
)

variant_glp1r       <- readRDS(file.path(PATHS$output_dir, "variant_details_glp1r.rds"))
variant_gipr        <- readRDS(file.path(PATHS$output_dir, "variant_details_gipr.rds"))

aou_results         <- tryCatch(
  readRDS(file.path(PATHS$output_dir, "allofus", "aou_results_primary.rds")),
  error = function(e) { cat("AoU results not found; skipping AoU figure.\n"); NULL }
)


###############################################################################
# COMPUTE RESPONSE RATIOS (CARRIER/CONTROL WEIGHT LOSS RATIO)
#
# relative_effect = mean_carrier / mean_control
# Both values are typically negative (weight loss); ratio < 1 = attenuation.
# CI on ratio: (mean_control + ci_lo/hi) / mean_control  (delta method)
###############################################################################

add_relative_effect <- function(df) {
  df %>% mutate(
    relative_effect   = case_when(
      is.na(mean_control) | mean_control >= 0 | is.na(mean_carrier) ~ NA_real_,
      TRUE ~ mean_carrier / mean_control
    ),
    # mean_control < 0, so dividing by it flips the inequality:
    # ci_hi (upper regression CI) maps to the LOWER ratio bound
    # ci_lo (lower regression CI) maps to the UPPER ratio bound
    relative_ci_lower = case_when(
      is.na(mean_control) | mean_control >= 0 ~ NA_real_,
      TRUE ~ pmax((mean_control + ci_hi) / mean_control, 0.01)
    ),
    relative_ci_upper = case_when(
      is.na(mean_control) | mean_control >= 0 ~ NA_real_,
      TRUE ~ pmin((mean_control + ci_lo) / mean_control, 10)
    ),
    ratio_nc = !is.na(mean_carrier) & mean_carrier >= 0
  )
}

all_results <- bind_rows(results_primary, results_subgroup) %>%
  distinct(analysis, .keep_all = TRUE) %>%
  add_relative_effect()


###############################################################################
# FOREST PLOT WITH RESPONSE RATIO AND EMBEDDED TABLE
#
# forest_rows: tibble with columns analysis, display_label, drug_group
#   Rows are ordered bottom-to-top (first row = y=1 = bottom of plot).
#   HEADER_ rows are printed bold; display_label is used for the y-axis tick.
###############################################################################

make_forest_with_table <- function(forest_rows,
                                   color_overall = COLORS$blue,
                                   color_sema    = COLORS$semaglutide,
                                   color_tirz    = COLORS$tirzepatide) {
  x_min      <- 0
  x_max      <- 2.85    # total width including embedded table
  forest_max <- 1.6     # CI clipped at this value
  col_n_x      <- 1.75
  col_weight_x <- 2.20
  col_ratio_x  <- 2.63

  fd <- forest_rows %>%
    left_join(
      all_results %>% select(analysis, n_carriers, n_controls,
                             mean_carrier, mean_control,
                             relative_effect, relative_ci_lower,
                             relative_ci_upper, ratio_nc, ci_lo, ci_hi),
      by = "analysis"
    ) %>%
    mutate(
      is_header  = grepl("^HEADER_", analysis),
      is_primary = display_label == "Any primary coding variant",
      point_color = case_when(
        drug_group == "overall"     ~ color_overall,
        drug_group == "semaglutide" ~ color_sema,
        drug_group == "tirzepatide" ~ color_tirz,
        TRUE ~ "black"
      ),
      col_n = case_when(
        is_header        ~ "",
        is.na(n_carriers) ~ "\u2014",
        TRUE             ~ sprintf("%d/%d", n_carriers, n_controls)
      ),
      col_weight = case_when(
        is_header           ~ "",
        is.na(mean_carrier) ~ "\u2014",
        mean_carrier > 0    ~ sprintf("+%.1f / %.1f",  mean_carrier, mean_control),
        mean_control > 0    ~ sprintf("%.1f / +%.1f",  mean_carrier, mean_control),
        TRUE                ~ sprintf("%.1f / %.1f",   mean_carrier, mean_control)
      ),
      col_ratio = case_when(
        is_header                                      ~ "",
        !is.na(ratio_nc) & ratio_nc                   ~ sprintf("NC (NC\u2013%.2f)",
                                                                 relative_ci_upper),
        is.na(relative_effect)                        ~ "\u2014",
        TRUE                                          ~ sprintf("%.2f (%.2f\u2013%.2f)",
                                                                 relative_effect,
                                                                 relative_ci_lower,
                                                                 relative_ci_upper)
      ),
      analysis = factor(analysis, levels = analysis)
    )

  n_rows       <- nrow(fd)
  primary_pos  <- which(fd$is_primary)
  data_plot    <- fd %>% filter(!is_header, !is.na(relative_effect))
  data_nc      <- fd %>% filter(!is_header, !is.na(ratio_nc) & ratio_nc)

  p <- ggplot(fd, aes(y = analysis)) +
    geom_vline(xintercept = 1.0, linetype = "dashed", colour = "gray40",
               linewidth = 0.6)

  for (pos in primary_pos) {
    p <- p + annotate("rect",
                      ymin = pos - 0.5, ymax = pos + 0.5,
                      xmin = x_min, xmax = x_max,
                      fill = "gray92", alpha = 1)
  }

  p <- p +
    geom_errorbarh(
      data = data_plot,
      aes(xmin = pmin(relative_ci_lower, forest_max),
          xmax = pmin(relative_ci_upper, forest_max),
          colour = point_color),
      height = 0.25, linewidth = 0.7
    ) +
    geom_point(
      data = data_plot,
      aes(x = pmin(relative_effect, forest_max), colour = point_color),
      size = 3, shape = 18
    )

  if (nrow(data_nc) > 0) {
    p <- p +
      geom_segment(data = data_nc,
                   aes(x = 0.06, xend = pmin(relative_ci_upper, forest_max),
                       y = analysis, yend = analysis, colour = point_color),
                   linewidth = 0.7) +
      geom_segment(data = data_nc,
                   aes(x = 0.06, xend = 0.01,
                       y = analysis, yend = analysis, colour = point_color),
                   arrow = arrow(length = unit(0.15, "cm"), type = "closed"),
                   linewidth = 0.7)
  }

  p <- p +
    scale_colour_identity() +
    geom_text(aes(x = col_n_x,      label = col_n),
              size = 2.5, hjust = 0.5, colour = "black", family = FONT_FAMILY) +
    geom_text(aes(x = col_weight_x, label = col_weight),
              size = 2.5, hjust = 0.5, colour = "black", family = FONT_FAMILY) +
    geom_text(data = fd %>% filter(!is_header),
              aes(x = col_ratio_x, label = col_ratio),
              size = 2.5, hjust = 0.5, colour = "black", family = FONT_FAMILY) +
    scale_x_continuous(
      breaks = seq(0, 1.4, 0.2),
      limits = c(x_min, x_max),
      labels = function(x) formatC(x, digits = 1, format = "f"),
      expand = expansion(mult = 0)
    ) +
    scale_y_discrete(
      labels = setNames(fd$display_label, as.character(fd$analysis)),
      drop   = FALSE
    ) +
    coord_cartesian(xlim = c(x_min, x_max), clip = "off") +
    labs(x = "Response ratio (carrier/control weight loss)", y = NULL) +
    annotate("text", x = col_n_x,      y = n_rows + 0.7,
             label = "n\ncarrier/control", size = 2.4, hjust = 0.5,
             fontface = "bold", colour = "black", family = FONT_FAMILY,
             lineheight = 0.85) +
    annotate("text", x = col_weight_x, y = n_rows + 0.7,
             label = "Weight change (%)\ncarrier/control", size = 2.4,
             hjust = 0.5, fontface = "bold", colour = "black",
             family = FONT_FAMILY, lineheight = 0.85) +
    annotate("text", x = col_ratio_x,  y = n_rows + 0.7,
             label = "Response ratio\n(95% CI)", size = 2.4, hjust = 0.5,
             fontface = "bold", colour = "black", family = FONT_FAMILY,
             lineheight = 0.85) +
    theme_minimal() +
    theme(
      panel.grid.major    = element_blank(),
      panel.grid.minor    = element_blank(),
      panel.background    = element_rect(fill = "white", colour = NA),
      plot.background     = element_rect(fill = "white", colour = NA),
      axis.line.x.bottom  = element_line(colour = "black", linewidth = 0.7),
      axis.line.y.left    = element_blank(),
      panel.border        = element_blank(),
      text                = element_text(size = 9, family = FONT_FAMILY,
                                         colour = "black"),
      axis.text.y         = element_text(
        size = 8, hjust = 0, margin = margin(r = 5),
        face = ifelse(fd$is_header, "bold", "plain")
      ),
      axis.text.x         = element_text(size = 8.5, colour = "black",
                                          margin = margin(t = 5)),
      axis.title.x        = element_text(size = 9.5, face = "bold",
                                          margin = margin(t = 10)),
      axis.ticks.x        = element_line(colour = "black", linewidth = 0.4),
      axis.ticks.y        = element_blank(),
      axis.ticks.length.x = unit(0.15, "cm"),
      plot.margin         = margin(10, 140, 10, 10)
    )

  p
}


###############################################################################
# FIGURE 1a — GLP1R FOREST PLOT (RESPONSE RATIO + EMBEDDED TABLE)
#
# Rows listed bottom-to-top: tirzepatide section → semaglutide → overall.
###############################################################################

glp1r_rows <- tribble(
  ~analysis,                                                           ~display_label,                   ~drug_group,
  # Tirzepatide section (bottom of plot)
  "GLP1R benign missense — tirzepatide (negative control)",            "  Benign (neg. control)",         "tirzepatide",
  "GLP1R uncertain missense — tirzepatide-specific",                   "  Uncertain missense",            "tirzepatide",
  "GLP1R rs146868158 — tirzepatide-specific",                          "  rs146868158",                   "tirzepatide",
  "GLP1R damaging missense — tirzepatide-specific",                    "  Damaging missense",             "tirzepatide",
  "GLP1R pLoF — tirzepatide-specific",                                 "  pLoF",                          "tirzepatide",
  "GLP1R primary — tirzepatide-specific",                              "Any primary coding variant",      "tirzepatide",
  "HEADER_TIRZEPATIDE",                                                "GLP1R, tirzepatide",              "tirzepatide",
  # Semaglutide section
  "GLP1R benign missense — semaglutide (negative control)",            "  Benign (neg. control)",         "semaglutide",
  "GLP1R uncertain missense — semaglutide",                            "  Uncertain missense",            "semaglutide",
  "GLP1R rs146868158 — semaglutide",                                   "  rs146868158",                   "semaglutide",
  "GLP1R damaging missense — semaglutide",                             "  Damaging missense",             "semaglutide",
  "GLP1R pLoF — semaglutide",                                          "  pLoF",                          "semaglutide",
  "GLP1R primary — semaglutide",                                       "Any primary coding variant",      "semaglutide",
  "HEADER_SEMAGLUTIDE",                                                "GLP1R, semaglutide",              "semaglutide",
  # Overall section (top)
  "GLP1R benign missense — overall (negative control)",                "  Benign (neg. control)",         "overall",
  "GLP1R uncertain missense — overall",                                "  Uncertain missense",            "overall",
  "GLP1R rs146868158 — overall",                                       "  rs146868158",                   "overall",
  "GLP1R damaging missense — overall",                                 "  Damaging missense",             "overall",
  "GLP1R pLoF — overall",                                              "  pLoF",                          "overall",
  "GLP1R primary — overall",                                           "Any primary coding variant",      "overall",
  "HEADER_OVERALL",                                                    "GLP1R, overall",                  "overall"
)

fig1a <- make_forest_with_table(glp1r_rows)
save_fig(fig1a, "fig1a_forest_glp1r", width = 10, height = 9)


###############################################################################
# FIGURE 1c — DRUG-STRATIFIED WEIGHT CHANGE COMPARISON
#
# Shows individual-level weight change distributions for carriers vs matched
# controls, separately for semaglutide and tirzepatide.
###############################################################################

# Create one violin panel for a single drug (matches Fig 1B style from manuscript)
create_violin_panel <- function(matched_df, carrier_var, drug_name, gene_label = "GLP1R") {
  color_carrier <- COLORS$pink
  color_control <- COLORS$green

  plot_data <- matched_df %>%
    filter(drug == tolower(drug_name)) %>%
    mutate(
      group = if_else(.data[[carrier_var]] == 1, "Carriers", "Matched controls"),
      group = factor(group, levels = c("Carriers", "Matched controls"))
    )

  if (nrow(plot_data) == 0) return(NULL)

  group_means <- plot_data %>%
    group_by(group) %>%
    summarise(
      mean_wt = weighted.mean(outcome_weight_pct_change, weights_att, na.rm = TRUE),
      .groups = "drop"
    )

  n_c <- sum(plot_data[[carrier_var]] == 1, na.rm = TRUE)
  n_k <- sum(plot_data[[carrier_var]] == 0, na.rm = TRUE)
  x_labels <- c(paste0("Carriers\n(n=", n_c, ")"),
                paste0("Matched controls\n(n=", n_k, ")"))

  ggplot(plot_data, aes(x = group, y = outcome_weight_pct_change, fill = group)) +
    geom_violin(alpha = 0.4, scale = "width", trim = TRUE,
                colour = "black", linewidth = 0.4, adjust = 1.2) +
    geom_boxplot(width = 0.15, alpha = 0.9, outlier.shape = NA,
                 colour = "black", linewidth = 0.6) +
    geom_jitter(width = 0.08, size = 1.5, alpha = 0.5, colour = "gray10") +
    geom_point(data = group_means,
               aes(x = group, y = mean_wt),
               shape = 23, size = 4, fill = "white", colour = "black",
               stroke = 1.5, inherit.aes = FALSE) +
    geom_text(data = group_means,
              aes(x = group, y = mean_wt,
                  label = sprintf("%.1f%%", mean_wt)),
              hjust = -0.45, size = 3.2, family = FONT_FAMILY,
              fontface = "bold", colour = "black", inherit.aes = FALSE) +
    scale_fill_manual(values = c("Carriers"        = color_carrier,
                                 "Matched controls" = color_control)) +
    scale_x_discrete(labels = x_labels) +
    scale_y_continuous(
      name   = if (drug_name == "Semaglutide") "Body weight change (%)" else NULL,
      breaks = c(-30, -20, -10, 0, 10),
      limits = c(-37, 12),
      labels = function(x) ifelse(x > 0, paste0("+", x), as.character(x)),
      expand = expansion(mult = c(0.02, 0.02))
    ) +
    labs(x = NULL, title = paste0(gene_label, ", ", tolower(drug_name))) +
    theme_minimal() +
    theme(
      panel.grid.major  = element_blank(),
      panel.grid.minor  = element_blank(),
      panel.background  = element_rect(fill = "white", colour = NA),
      plot.background   = element_rect(fill = "white", colour = NA),
      panel.border      = element_rect(fill = NA, colour = "black", linewidth = 0.8),
      text              = element_text(size = 11, family = FONT_FAMILY, colour = "black"),
      axis.text         = element_text(size = 10, colour = "black"),
      axis.text.x       = element_text(size = 10, face = "bold", lineheight = 1.1),
      axis.title        = element_text(size = 11, face = "bold"),
      axis.title.y      = if (drug_name == "Semaglutide")
                            element_text(margin = margin(r = 10)) else element_blank(),
      axis.line         = element_blank(),
      axis.ticks        = element_line(colour = "black", linewidth = 0.5),
      axis.ticks.length = unit(0.15, "cm"),
      plot.title        = element_text(size = 12, face = "bold", hjust = 0.5,
                                       colour = "black"),
      legend.position   = "none",
      plot.margin       = margin(15, 15, 10, 10)
    )
}

fig1c <- create_violin_panel(matched_glp1r, "carrier_primary", "Semaglutide") +
         create_violin_panel(matched_glp1r, "carrier_primary", "Tirzepatide") +
         plot_layout(ncol = 2, widths = c(1, 1))

save_fig(fig1c, "fig1c_drug_comparison", width = 9.71, height = 5.1)


###############################################################################
# FIGURE 1d — GLP1R SLOPEGRAPH
#
# Each line connects one carrier's weight change to the weighted mean weight
# change of their matched controls (within the same MatchIt subclass).
# Lines are coloured by variant class.
###############################################################################

# Variant class colors for slopegraph (matches Fig 1C in original manuscript)
slopegraph_colors <- c(
  "pLoF"              = COLORS$plof,
  "Damaging missense" = COLORS$damaging_missense,
  "rs146868158"       = COLORS$rs146868158,
  "Uncertain missense" = COLORS$green    # green for uncertain in slopegraph
)

create_slopegraph <- function(matched_df, drug_name, carrier_var = "carrier_primary",
                              variant_df     = variant_glp1r,
                              lof_col        = "has_lof",
                              dam_col        = "has_damaging_missense",
                              rs146_col      = "has_rs146",
                              unc_col        = "has_uncertain_missense",
                              gene_label     = "GLP1R") {
  drug_lc <- tolower(drug_name)

  carriers <- matched_df %>%
    filter(.data[[carrier_var]] == 1, drug == drug_lc) %>%
    select(person_source_value, carrier_wt = outcome_weight_pct_change, subclass)

  if (nrow(carriers) == 0) return(NULL)

  ctrl_means <- matched_df %>%
    filter(.data[[carrier_var]] == 0, drug == drug_lc) %>%
    group_by(subclass) %>%
    summarise(ctrl_mean_wt = weighted.mean(outcome_weight_pct_change, weights_att,
                                            na.rm = TRUE),
              .groups = "drop")

  # Select variant annotation columns that exist
  vcols <- c("person_source_value",
             lof_col, dam_col,
             if (!is.null(rs146_col)) rs146_col,
             unc_col)
  vcols <- intersect(vcols, names(variant_df))

  # Build factor levels for variant_type based on columns available
  vt_levels <- c("pLoF", "Damaging missense")
  if (!is.null(rs146_col) && rs146_col %in% names(variant_df)) {
    vt_levels <- c(vt_levels, "rs146868158")
  }
  vt_levels <- c(vt_levels, "Uncertain missense")

  joined <- carriers %>%
    left_join(ctrl_means, by = "subclass") %>%
    left_join(variant_df %>% select(all_of(vcols)), by = "person_source_value")

  has_rs146_col <- !is.null(rs146_col) && rs146_col %in% names(joined)

  if (has_rs146_col) {
    joined <- joined %>% mutate(
      variant_type = case_when(
        .data[[lof_col]]   == 1 ~ "pLoF",
        .data[[dam_col]]   == 1 ~ "Damaging missense",
        !is.na(.data[[rs146_col]]) & .data[[rs146_col]] == 1 ~ "rs146868158",
        .data[[unc_col]]   == 1 ~ "Uncertain missense",
        TRUE                    ~ "Uncertain missense"
      )
    )
  } else {
    joined <- joined %>% mutate(
      variant_type = case_when(
        .data[[lof_col]] == 1 ~ "pLoF",
        .data[[dam_col]] == 1 ~ "Damaging missense",
        .data[[unc_col]] == 1 ~ "Uncertain missense",
        TRUE                  ~ "Uncertain missense"
      )
    )
  }

  slope_df <- joined %>%
    mutate(
      variant_type = factor(variant_type, levels = vt_levels),
      carrier_id   = row_number()
    ) %>%
    filter(!is.na(ctrl_mean_wt))

  # Use only colours for variant types actually present
  sg_colors_use <- slopegraph_colors[names(slopegraph_colors) %in% vt_levels]

  # Reshape to long for geom_line
  long_df <- bind_rows(
    slope_df %>% select(carrier_id, variant_type, wt = carrier_wt) %>%
      mutate(side = "Carriers"),
    slope_df %>% select(carrier_id, variant_type, wt = ctrl_mean_wt) %>%
      mutate(side = "Matched control means")
  ) %>%
    mutate(side = factor(side, levels = c("Carriers", "Matched control means")))

  y_min <- -37; y_max <- 12; y_breaks <- seq(-30, 10, 10)

  ggplot(long_df, aes(x = side, y = wt, group = carrier_id)) +
    geom_line(aes(colour = variant_type), alpha = 0.6, linewidth = 0.9) +
    geom_point(aes(colour = variant_type, fill = variant_type),
               size = 2.8, alpha = 0.9, shape = 21, stroke = 0.5,
               colour = "black") +
    scale_colour_manual(values = sg_colors_use, name = "Variant type") +
    scale_fill_manual(values   = sg_colors_use, name = "Variant type") +
    scale_y_continuous(
      name   = if (drug_name == "Semaglutide") "Body weight change (%)" else NULL,
      breaks = y_breaks, limits = c(y_min, y_max),
      labels = function(x) ifelse(x > 0, paste0("+", x), as.character(x)),
      expand = expansion(mult = c(0.02, 0.02))
    ) +
    scale_x_discrete(expand = expansion(add = 0.3)) +
    labs(x = NULL, title = paste0(gene_label, ", ", drug_lc)) +
    theme_minimal() +
    theme(
      panel.grid.major  = element_blank(),
      panel.grid.minor  = element_blank(),
      panel.background  = element_rect(fill = "white", colour = NA),
      plot.background   = element_rect(fill = "white", colour = NA),
      panel.border      = element_rect(fill = NA, colour = "black", linewidth = 0.8),
      text              = element_text(size = 11, family = FONT_FAMILY,
                                       colour = "black"),
      axis.text         = element_text(size = 10, colour = "black"),
      axis.text.x       = element_text(size = 10, face = "bold"),
      axis.title        = element_text(size = 11, face = "bold"),
      axis.title.y      = if (drug_name == "Semaglutide")
                            element_text(margin = margin(r = 10)) else element_blank(),
      axis.line         = element_blank(),
      axis.ticks        = element_line(colour = "black", linewidth = 0.5),
      axis.ticks.length = unit(0.15, "cm"),
      plot.title        = element_text(size = 12, face = "bold", hjust = 0.5,
                                       colour = "black"),
      legend.position   = c(0.80, 0.15),
      legend.background = element_rect(fill = "white", colour = NA),
      legend.key.size   = unit(0.4, "cm"),
      legend.text       = element_text(size = 8),
      legend.title      = element_text(size = 9, face = "bold"),
      plot.margin       = margin(10, 10, 10, 10)
    )
}

fig1d_sema <- create_slopegraph(matched_glp1r, "Semaglutide")
fig1d_tirz <- create_slopegraph(matched_glp1r, "Tirzepatide")

if (!is.null(fig1d_sema) && !is.null(fig1d_tirz)) {
  fig1d <- fig1d_sema + fig1d_tirz + plot_layout(ncol = 2, widths = c(1, 1))
  save_fig(fig1d, "fig1d_slopegraph_glp1r", width = 9.71, height = 5.1)
} else {
  cat("Slopegraph skipped: no GLP1R primary carriers in matched data.\n")
}


###############################################################################
# FIGURE 1b — GIPR FOREST PLOT (RESPONSE RATIO + EMBEDDED TABLE)
#
# Mirrors Fig 1a (GLP1R) but for GIPR:
#   Overall: primary, pLoF+damaging, uncertain, benign (neg. control)
#   Sema:    primary, pLoF+damaging, uncertain
#   Tirz:    primary, pLoF+damaging, uncertain
# (No rs146868158 equivalent for GIPR)
###############################################################################

gipr_rows <- tribble(
  ~analysis,                                                           ~display_label,                  ~drug_group,
  # Tirzepatide section (bottom)
  "GIPR benign missense — tirzepatide (negative control)",             "  Benign (neg. control)",        "tirzepatide",
  "GIPR uncertain missense — tirzepatide-specific",                    "  Uncertain missense",           "tirzepatide",
  "GIPR damaging missense — tirzepatide-specific",                     "  Damaging missense",            "tirzepatide",
  "GIPR pLoF — tirzepatide-specific",                                  "  pLoF",                         "tirzepatide",
  "GIPR primary — tirzepatide-specific",                               "Any primary coding variant",     "tirzepatide",
  "HEADER_TIRZEPATIDE",                                                "GIPR, tirzepatide",              "tirzepatide",
  # Semaglutide section
  "GIPR benign missense — semaglutide (negative control)",             "  Benign (neg. control)",        "semaglutide",
  "GIPR uncertain missense — semaglutide",                             "  Uncertain missense",           "semaglutide",
  "GIPR damaging missense — semaglutide",                              "  Damaging missense",            "semaglutide",
  "GIPR pLoF — semaglutide",                                           "  pLoF",                         "semaglutide",
  "GIPR primary — semaglutide",                                        "Any primary coding variant",     "semaglutide",
  "HEADER_SEMAGLUTIDE",                                                "GIPR, semaglutide",              "semaglutide",
  # Overall section (top)
  "GIPR benign missense — overall (negative control)",                 "  Benign (neg. control)",        "overall",
  "GIPR uncertain missense — overall",                                 "  Uncertain missense",           "overall",
  "GIPR damaging missense — overall",                                  "  Damaging missense",            "overall",
  "GIPR pLoF — overall",                                               "  pLoF",                         "overall",
  "GIPR primary — overall",                                            "Any primary coding variant",     "overall",
  "HEADER_OVERALL",                                                    "GIPR, overall",                  "overall"
)

fig1b_gipr <- make_forest_with_table(gipr_rows)
save_fig(fig1b_gipr, "fig1b_forest_gipr", width = 10, height = 9)


###############################################################################
# SUPPLEMENTARY — GIPR VIOLIN/BOX PLOTS (mirrors Fig 1c for GIPR)
###############################################################################

supp_gipr_sema <- create_violin_panel(matched_gipr, "carrier_gipr_primary",
                                      "Semaglutide", gene_label = "GIPR")
supp_gipr_tirz <- create_violin_panel(matched_gipr, "carrier_gipr_primary",
                                      "Tirzepatide", gene_label = "GIPR")

if (!is.null(supp_gipr_sema) && !is.null(supp_gipr_tirz)) {
  supp_gipr_violin <- supp_gipr_sema + supp_gipr_tirz +
    plot_layout(ncol = 2, widths = c(1, 1))
  save_fig(supp_gipr_violin, "supp_fig_gipr_violin", width = 9.71, height = 5.1)
} else {
  cat("GIPR violin skipped: no GIPR primary carriers in matched data.\n")
}


###############################################################################
# SUPPLEMENTARY — GIPR SLOPEGRAPH (mirrors Fig 1d for GIPR)
###############################################################################

supp_gipr_slope_sema <- create_slopegraph(
  matched_gipr, "Semaglutide",
  carrier_var = "carrier_gipr_primary",
  variant_df  = variant_gipr,
  lof_col     = "has_gipr_lof",
  dam_col     = "has_gipr_damaging_missense",
  rs146_col   = NULL,
  unc_col     = "has_gipr_uncertain_missense",
  gene_label  = "GIPR"
)
supp_gipr_slope_tirz <- create_slopegraph(
  matched_gipr, "Tirzepatide",
  carrier_var = "carrier_gipr_primary",
  variant_df  = variant_gipr,
  lof_col     = "has_gipr_lof",
  dam_col     = "has_gipr_damaging_missense",
  rs146_col   = NULL,
  unc_col     = "has_gipr_uncertain_missense",
  gene_label  = "GIPR"
)

if (!is.null(supp_gipr_slope_sema) && !is.null(supp_gipr_slope_tirz)) {
  supp_gipr_slopegraph <- supp_gipr_slope_sema + supp_gipr_slope_tirz +
    plot_layout(ncol = 2, widths = c(1, 1))
  save_fig(supp_gipr_slopegraph, "supp_fig_gipr_slopegraph", width = 9.71, height = 5.1)
} else {
  cat("GIPR slopegraph skipped: no GIPR primary carriers in matched data.\n")
}


###############################################################################
# SUPPLEMENTARY — GLP1R CLINICAL SUBGROUP FOREST PLOT
#
# 9 subgroups × 3 drug groups + 3 headers = 30 rows.
# Mirrors the structure of glp1r_subgroups_fig1a.R from the original analysis.
# Subgroups: T2D, No T2D, Male, Female, GLP-1 naive, GLP-1 experienced,
#            BMI <40, BMI ≥40, high dose.
###############################################################################

glp1r_subgroup_rows <- tribble(
  ~analysis,                                                         ~display_label,              ~drug_group,
  # Tirzepatide section (bottom)
  "GLP1R primary — high dose, tirzepatide-specific",                 "High dose (\u226510 mg)",   "tirzepatide",
  "GLP1R primary — BMI \u226540, tirzepatide-specific",              "BMI \u226540 kg/m\u00b2",   "tirzepatide",
  "GLP1R primary — BMI <40, tirzepatide-specific",                   "BMI <40 kg/m\u00b2",        "tirzepatide",
  "GLP1R primary — Male, tirzepatide-specific",                      "Male",                      "tirzepatide",
  "GLP1R primary — Female, tirzepatide-specific",                    "Female",                    "tirzepatide",
  "GLP1R primary — GLP-1 experienced, tirzepatide-specific",         "Has prior GLP-1 RA",        "tirzepatide",
  "GLP1R primary — GLP-1 naive, tirzepatide-specific",               "No prior GLP-1 RA",         "tirzepatide",
  "GLP1R primary — T2D, tirzepatide-specific",                       "Has type 2 diabetes",       "tirzepatide",
  "GLP1R primary — No T2D, tirzepatide-specific",                    "No type 2 diabetes",        "tirzepatide",
  "HEADER_TIRZ_SG",                                                  "GLP1R, tirzepatide",        "tirzepatide",
  # Semaglutide section
  "GLP1R primary — high dose, semaglutide",                          "High dose (\u22651.7 mg)",  "semaglutide",
  "GLP1R primary — BMI \u226540, semaglutide",                       "BMI \u226540 kg/m\u00b2",   "semaglutide",
  "GLP1R primary — BMI <40, semaglutide",                            "BMI <40 kg/m\u00b2",        "semaglutide",
  "GLP1R primary — Male, semaglutide",                               "Male",                      "semaglutide",
  "GLP1R primary — Female, semaglutide",                             "Female",                    "semaglutide",
  "GLP1R primary — GLP-1 experienced, semaglutide",                  "Has prior GLP-1 RA",        "semaglutide",
  "GLP1R primary — GLP-1 naive, semaglutide",                        "No prior GLP-1 RA",         "semaglutide",
  "GLP1R primary — T2D, semaglutide",                                "Has type 2 diabetes",       "semaglutide",
  "GLP1R primary — No T2D, semaglutide",                             "No type 2 diabetes",        "semaglutide",
  "HEADER_SEMA_SG",                                                  "GLP1R, semaglutide",        "semaglutide",
  # Overall section (top)
  "GLP1R primary — high dose, overall",                              "High dose",                 "overall",
  "GLP1R primary — BMI \u226540, overall",                           "BMI \u226540 kg/m\u00b2",   "overall",
  "GLP1R primary — BMI <40, overall",                                "BMI <40 kg/m\u00b2",        "overall",
  "GLP1R primary — Male, overall",                                   "Male",                      "overall",
  "GLP1R primary — Female, overall",                                 "Female",                    "overall",
  "GLP1R primary — GLP-1 experienced, overall",                      "Has prior GLP-1 RA",        "overall",
  "GLP1R primary — GLP-1 naive, overall",                            "No prior GLP-1 RA",         "overall",
  "GLP1R primary — T2D, overall",                                    "Has type 2 diabetes",       "overall",
  "GLP1R primary — No T2D, overall",                                 "No type 2 diabetes",        "overall",
  "HEADER_OVERALL_SG",                                               "GLP1R, overall",            "overall"
)

ed_subgroup_glp1r <- make_forest_with_table(glp1r_subgroup_rows)
save_fig(ed_subgroup_glp1r, "ed_fig_subgroup_glp1r", width = 10, height = 12)


###############################################################################
# SUPPLEMENTARY — GIPR CLINICAL SUBGROUP FOREST PLOT
#
# 9 subgroups × 3 drug groups + 3 headers = 30 rows.
# Mirrors the structure of gipr_subgroups_fig.R from the original analysis.
###############################################################################

gipr_subgroup_rows <- tribble(
  ~analysis,                                                         ~display_label,              ~drug_group,
  # Tirzepatide section (bottom)
  "GIPR primary — high dose, tirzepatide-specific",                  "High dose (\u226510 mg)",   "tirzepatide",
  "GIPR primary — BMI \u226540, tirzepatide-specific",               "BMI \u226540 kg/m\u00b2",   "tirzepatide",
  "GIPR primary — BMI <40, tirzepatide-specific",                    "BMI <40 kg/m\u00b2",        "tirzepatide",
  "GIPR primary — Male, tirzepatide-specific",                       "Male",                      "tirzepatide",
  "GIPR primary — Female, tirzepatide-specific",                     "Female",                    "tirzepatide",
  "GIPR primary — GLP-1 experienced, tirzepatide-specific",          "Has prior GLP-1 RA",        "tirzepatide",
  "GIPR primary — GLP-1 naive, tirzepatide-specific",                "No prior GLP-1 RA",         "tirzepatide",
  "GIPR primary — T2D, tirzepatide-specific",                        "Has type 2 diabetes",       "tirzepatide",
  "GIPR primary — No T2D, tirzepatide-specific",                     "No type 2 diabetes",        "tirzepatide",
  "HEADER_TIRZ_SG_GIPR",                                             "GIPR, tirzepatide",         "tirzepatide",
  # Semaglutide section
  "GIPR primary — high dose, semaglutide",                           "High dose (\u22651.7 mg)",  "semaglutide",
  "GIPR primary — BMI \u226540, semaglutide",                        "BMI \u226540 kg/m\u00b2",   "semaglutide",
  "GIPR primary — BMI <40, semaglutide",                             "BMI <40 kg/m\u00b2",        "semaglutide",
  "GIPR primary — Male, semaglutide",                                "Male",                      "semaglutide",
  "GIPR primary — Female, semaglutide",                              "Female",                    "semaglutide",
  "GIPR primary — GLP-1 experienced, semaglutide",                   "Has prior GLP-1 RA",        "semaglutide",
  "GIPR primary — GLP-1 naive, semaglutide",                         "No prior GLP-1 RA",         "semaglutide",
  "GIPR primary — T2D, semaglutide",                                 "Has type 2 diabetes",       "semaglutide",
  "GIPR primary — No T2D, semaglutide",                              "No type 2 diabetes",        "semaglutide",
  "HEADER_SEMA_SG_GIPR",                                             "GIPR, semaglutide",         "semaglutide",
  # Overall section (top)
  "GIPR primary — high dose, overall",                               "High dose",                 "overall",
  "GIPR primary — BMI \u226540, overall",                            "BMI \u226540 kg/m\u00b2",   "overall",
  "GIPR primary — BMI <40, overall",                                 "BMI <40 kg/m\u00b2",        "overall",
  "GIPR primary — Male, overall",                                    "Male",                      "overall",
  "GIPR primary — Female, overall",                                  "Female",                    "overall",
  "GIPR primary — GLP-1 experienced, overall",                       "Has prior GLP-1 RA",        "overall",
  "GIPR primary — GLP-1 naive, overall",                             "No prior GLP-1 RA",         "overall",
  "GIPR primary — T2D, overall",                                     "Has type 2 diabetes",       "overall",
  "GIPR primary — No T2D, overall",                                  "No type 2 diabetes",        "overall",
  "HEADER_OVERALL_SG_GIPR",                                          "GIPR, overall",             "overall"
)

ed_subgroup_gipr <- make_forest_with_table(gipr_subgroup_rows)
save_fig(ed_subgroup_gipr, "ed_fig_subgroup_gipr", width = 10, height = 12)


###############################################################################
# EXTENDED DATA — REGENIE SENSITIVITY
###############################################################################

if (!is.null(results_regenie) && nrow(results_regenie) > 0) {
  ed_regenie <- results_regenie %>%
    mutate(
      mask_label = case_when(
        grepl("M1_pLoF",          ID) ~ "pLoF",
        grepl("M2_pLoF_damaging", ID) ~ "pLoF + damaging",
        grepl("M3_primary",       ID) ~ "Primary (all functional)",
        TRUE                         ~ ID
      ),
      gene  = if_else(grepl("GLP1R", analysis), "GLP1R", "GIPR"),
      sig   = p_value < PARAMS$alpha,
      ci_lo = BETA - 1.96 * SE,
      ci_hi = BETA + 1.96 * SE
    ) %>%
    ggplot(aes(x = BETA, xmin = ci_lo, xmax = ci_hi,
               y = fct_rev(fct_inorder(mask_label)))) +
    geom_vline(xintercept = 0, linetype = "dashed", linewidth = 0.4,
               colour = "grey50") +
    geom_errorbarh(colour = "grey40", height = 0.2, linewidth = 0.5) +
    geom_point(aes(shape = sig), colour = COLORS$blue, size = 2) +
    scale_shape_manual(values = c("TRUE" = 16, "FALSE" = 1),
                       labels = c("TRUE" = paste0("p<", PARAMS$alpha),
                                  "FALSE" = "n.s."),
                       name = NULL) +
    scale_x_continuous(name = "BETA (RINT weight change, regenie)") +
    scale_y_discrete(name = NULL) +
    facet_wrap(~gene, scales = "free_y") +
    labs(title = "Regenie burden test sensitivity (Europeans only)") +
    theme_paper()

  save_fig(ed_regenie, "ed_fig_regenie", width = 9.71, height = 4.5)
} else {
  cat("Regenie results not available; skipping ed_fig_regenie.\n")
}


###############################################################################
# EXTENDED DATA — ALL OF US REPLICATION
###############################################################################

if (!is.null(aou_results) && nrow(aou_results) > 0) {
  aou_plot_data <- aou_results %>%
    mutate(
      label = str_replace(analysis, "AoU ", ""),
      drug_group = case_when(
        grepl("semaglutide", analysis, ignore.case = TRUE) ~ "semaglutide",
        grepl("tirzepatide", analysis, ignore.case = TRUE) ~ "tirzepatide",
        TRUE                                               ~ "overall"
      ),
      significant = if_else(p_value < PARAMS$alpha, "yes", "no"),
      cohort = "All of Us"
    )

  # Combine with HRN primary for side-by-side comparison
  hrn_for_compare <- results_primary %>%
    filter(grepl("GLP1R primary", analysis),
           !grepl("within overall|benign", analysis)) %>%
    mutate(
      label = str_replace(analysis, "GLP1R primary — ", ""),
      drug_group = case_when(
        grepl("semaglutide", analysis, ignore.case = TRUE) ~ "semaglutide",
        grepl("tirzepatide", analysis, ignore.case = TRUE) ~ "tirzepatide",
        TRUE                                               ~ "overall"
      ),
      significant = if_else(p_value < PARAMS$alpha, "yes", "no"),
      cohort = "HRN (primary)"
    )

  compare_df <- bind_rows(hrn_for_compare, aou_plot_data) %>%
    filter(!is.na(estimate))

  ed_aou <- compare_df %>%
    ggplot(aes(x = estimate, xmin = ci_lo, xmax = ci_hi,
               y = fct_rev(fct_inorder(label)),
               colour = cohort, shape = cohort)) +
    geom_vline(xintercept = 0, linetype = "dashed", linewidth = 0.4,
               colour = "grey50") +
    geom_errorbarh(height = 0.2, linewidth = 0.5,
                   position = position_dodge(width = 0.5)) +
    geom_point(size = 2, position = position_dodge(width = 0.5)) +
    scale_colour_manual(
      values = c("HRN (primary)" = COLORS$blue, "All of Us" = COLORS$pink),
      name = NULL
    ) +
    scale_shape_manual(values = c("HRN (primary)" = 16, "All of Us" = 17),
                       name = NULL) +
    facet_wrap(~drug_group, ncol = 3) +
    scale_x_continuous(name = "Difference in weight change (carrier vs control, pp)") +
    scale_y_discrete(name = NULL) +
    labs(title = "GLP1R primary carriers: HRN vs All of Us replication") +
    theme_paper() +
    theme(legend.position = "top")

  save_fig(ed_aou, "ed_fig_aou", width = 9.71, height = 5.1)
} else {
  cat("AoU results not available; skipping ed_fig_aou.\n")
}


###############################################################################
# TABLE 1 — BASELINE CHARACTERISTICS (PRE- AND POST-MATCH)
#
# Two separate tables: GLP1R primary carriers and GIPR primary carriers.
# Columns: Carriers - Pre | Non-Carriers - Pre | SMD - Pre |
#          Carriers - Post | Controls - Post | SMD - Post
#
# Pre-match pool loaded from analysis_overall.rds (output of 03_outcome_definition.R).
# Post-match data from matched_glp1r / matched_gipr (output of 04_matching.R).
###############################################################################

analysis_overall <- readRDS(file.path(PATHS$output_dir, "analysis_overall.rds"))

# Helper: compute mean(SD) or n(%) with optional ATT weights
t1_stats <- function(data, var, weighted = TRUE, weights_var = "weights_att",
                     group_var, default = "\u2014") {
  tryCatch({
    if (!var %in% names(data)) return(list(carrier = default, control = default))
    c_dat <- data[data[[group_var]] == 1, ]
    k_dat <- data[data[[group_var]] == 0, ]
    w_c   <- if (weighted && weights_var %in% names(c_dat)) c_dat[[weights_var]] else rep(1, nrow(c_dat))
    w_k   <- if (weighted && weights_var %in% names(k_dat)) k_dat[[weights_var]] else rep(1, nrow(k_dat))
    if (is.numeric(data[[var]])) {
      m_c <- weighted.mean(c_dat[[var]], w_c, na.rm = TRUE)
      s_c <- sqrt(weighted.mean((c_dat[[var]] - m_c)^2, w_c, na.rm = TRUE))
      m_k <- weighted.mean(k_dat[[var]], w_k, na.rm = TRUE)
      s_k <- sqrt(weighted.mean((k_dat[[var]] - m_k)^2, w_k, na.rm = TRUE))
      list(carrier = sprintf("%.1f (%.1f)", m_c, s_c),
           control = sprintf("%.1f (%.1f)", m_k, s_k))
    } else {
      ref   <- sort(unique(na.omit(data[[var]])))[1]
      n_c   <- sum(c_dat[[var]] == ref, na.rm = TRUE)
      n_k   <- sum(k_dat[[var]] == ref, na.rm = TRUE)
      pct_c <- 100 * sum(w_c[c_dat[[var]] == ref], na.rm = TRUE) / sum(w_c, na.rm = TRUE)
      pct_k <- 100 * sum(w_k[k_dat[[var]] == ref], na.rm = TRUE) / sum(w_k, na.rm = TRUE)
      list(carrier = sprintf("%d (%.1f)", n_c, pct_c),
           control = sprintf("%d (%.1f)", n_k, pct_k))
    }
  }, error = function(e) list(carrier = default, control = default))
}

# Inline SMD for variables not in balance_summary
t1_smd_inline <- function(data, var, group_var, weighted = FALSE,
                           weights_var = "weights_att") {
  tryCatch({
    if (!var %in% names(data)) return("")
    c_dat <- data[data[[group_var]] == 1, ]
    k_dat <- data[data[[group_var]] == 0, ]
    w_k   <- if (weighted && weights_var %in% names(k_dat)) k_dat[[weights_var]] else rep(1, nrow(k_dat))
    x_c   <- as.numeric(c_dat[[var]])
    x_k   <- as.numeric(k_dat[[var]])
    m_c   <- mean(x_c, na.rm = TRUE)
    m_k   <- if (weighted) weighted.mean(x_k, w_k, na.rm = TRUE) else mean(x_k, na.rm = TRUE)
    v_c   <- mean((x_c - m_c)^2, na.rm = TRUE)
    v_k   <- if (weighted) weighted.mean((x_k - m_k)^2, w_k, na.rm = TRUE) else mean((x_k - m_k)^2, na.rm = TRUE)
    ps    <- sqrt((v_c + v_k) / 2)
    if (is.na(ps) || ps == 0) return("0.000")
    sprintf("%.3f", abs(m_c - m_k) / ps)
  }, error = function(e) "")
}

# Get post-match SMD from balance_summary
get_bal_smd <- function(analysis_label, var) {
  tryCatch({
    val <- balance_summary %>%
      filter(analysis == analysis_label, variable == var) %>%
      pull(smd)
    if (length(val) == 0 || all(is.na(val))) return("")
    sprintf("%.3f", abs(val[1]))
  }, error = function(e) "")
}

make_row_t1 <- function(label, pre_c = "\u2014", pre_k = "\u2014", smd_pre = "",
                         post_c, post_k, smd_post = "") {
  list(Variable = label, `Carriers - Pre` = pre_c, `Non-Carriers - Pre` = pre_k,
       `SMD - Pre` = smd_pre, `Carriers - Post` = post_c,
       `Controls - Post` = post_k, `SMD - Post` = smd_post)
}
header_t1 <- function(label) make_row_t1(label, post_c = "", post_k = "")

build_table1 <- function(prematch_df, matched_df, carrier_var,
                          bal_label, gene_label) {

  n_c_pre  <- sum(prematch_df[[carrier_var]] == 1, na.rm = TRUE)
  n_k_pre  <- sum(prematch_df[[carrier_var]] == 0, na.rm = TRUE)
  n_c_post <- sum(matched_df[[carrier_var]]  == 1, na.rm = TRUE)
  n_k_post <- sum(matched_df[[carrier_var]]  == 0, na.rm = TRUE)

  rows <- list()
  r <- 1

  rows[[r]] <- make_row_t1("N",
    as.character(n_c_pre), as.character(n_k_pre), "",
    as.character(n_c_post), as.character(n_k_post), "")
  r <- r + 1

  rows[[r]] <- header_t1("Demographics"); r <- r + 1

  # Age
  pre  <- t1_stats(prematch_df, "age", weighted = FALSE, group_var = carrier_var)
  post <- t1_stats(matched_df,  "age", group_var = carrier_var)
  rows[[r]] <- make_row_t1("  Age, years",
    pre$carrier, pre$control, t1_smd_inline(prematch_df, "age", carrier_var),
    post$carrier, post$control, get_bal_smd(bal_label, "age"))
  r <- r + 1

  # Sex (Female; "F" is alphabetically first)
  pre  <- t1_stats(prematch_df, "sex", weighted = FALSE, group_var = carrier_var)
  post <- t1_stats(matched_df,  "sex", group_var = carrier_var)
  rows[[r]] <- make_row_t1("  Female, n (%)",
    pre$carrier, pre$control, t1_smd_inline(prematch_df, "sex", carrier_var),
    post$carrier, post$control, get_bal_smd(bal_label, "sex"))
  r <- r + 1

  # Genetic similarity — header then one row per level
  rows[[r]] <- make_row_t1("  Genetic similarity, n (%)",
    post_c = "", post_k = ""); r <- r + 1

  anc_levels <- c("European", "African", "Americas", "EastAsian", "SouthAsian", "Other")
  anc_labels <- c("    European", "    African", "    Americas",
                  "    East Asian", "    South Asian", "    Other")
  for (i in seq_along(anc_levels)) {
    anc <- anc_levels[i]
    # Pre
    c_n_pre <- sum(prematch_df[[carrier_var]] == 1 & prematch_df$ancestry_group == anc, na.rm = TRUE)
    k_n_pre <- sum(prematch_df[[carrier_var]] == 0 & prematch_df$ancestry_group == anc, na.rm = TRUE)
    # Post
    c_n_post_a <- sum(matched_df[[carrier_var]] == 1 & matched_df$ancestry_group == anc, na.rm = TRUE)
    k_n_post_a <- sum(matched_df[[carrier_var]] == 0 & matched_df$ancestry_group == anc, na.rm = TRUE)
    w_k_anc    <- sum(matched_df$weights_att[matched_df[[carrier_var]] == 0 &
                        matched_df$ancestry_group == anc], na.rm = TRUE)
    w_k_tot    <- sum(matched_df$weights_att[matched_df[[carrier_var]] == 0], na.rm = TRUE)
    # Inline SMD (binary: this ancestry)
    bin_pre  <- t1_smd_inline(
      prematch_df %>% mutate(.a = as.integer(ancestry_group == anc)), ".a", carrier_var)
    bin_post <- t1_smd_inline(
      matched_df  %>% mutate(.a = as.integer(ancestry_group == anc)), ".a", carrier_var,
      weighted = TRUE)
    rows[[r]] <- make_row_t1(anc_labels[i],
      sprintf("%d (%.1f)", c_n_pre, 100 * c_n_pre / max(n_c_pre, 1)),
      sprintf("%d (%.1f)", k_n_pre, 100 * k_n_pre / max(n_k_pre, 1)),
      bin_pre,
      sprintf("%d (%.1f)", c_n_post_a, 100 * c_n_post_a / max(n_c_post, 1)),
      sprintf("%d (%.1f)", k_n_post_a, 100 * w_k_anc / max(w_k_tot, 1)),
      bin_post)
    r <- r + 1
  }

  rows[[r]] <- header_t1("Baseline Anthropometrics"); r <- r + 1

  # BMI
  pre  <- t1_stats(prematch_df, "bmi_baseline", weighted = FALSE, group_var = carrier_var)
  post <- t1_stats(matched_df,  "bmi_baseline", group_var = carrier_var)
  rows[[r]] <- make_row_t1("  BMI, kg/m\u00b2",
    pre$carrier, pre$control, t1_smd_inline(prematch_df, "bmi_baseline", carrier_var),
    post$carrier, post$control, get_bal_smd(bal_label, "bmi_baseline"))
  r <- r + 1

  # Weight (kg) if available
  wt_var <- intersect(c("weight_baseline_kg", "weight_baseline_value"), names(matched_df))[1]
  if (!is.na(wt_var)) {
    pre  <- t1_stats(prematch_df, wt_var, weighted = FALSE, group_var = carrier_var)
    post <- t1_stats(matched_df,  wt_var, group_var = carrier_var)
    rows[[r]] <- make_row_t1("  Weight, kg",
      pre$carrier, pre$control, t1_smd_inline(prematch_df, wt_var, carrier_var),
      post$carrier, post$control, t1_smd_inline(matched_df, wt_var, carrier_var, weighted = TRUE))
    r <- r + 1
  }

  rows[[r]] <- header_t1("Comorbidities"); r <- r + 1

  # T2D (1 = yes; recode so 1 is ref for stats)
  t2d_pre  <- prematch_df %>% mutate(diabetes_type2 = factor(diabetes_type2, levels = c(1, 0)))
  t2d_post <- matched_df  %>% mutate(diabetes_type2 = factor(diabetes_type2, levels = c(1, 0)))
  pre  <- t1_stats(t2d_pre,  "diabetes_type2", weighted = FALSE, group_var = carrier_var)
  post <- t1_stats(t2d_post, "diabetes_type2", group_var = carrier_var)
  rows[[r]] <- make_row_t1("  Type 2 diabetes, n (%)",
    pre$carrier, pre$control,
    t1_smd_inline(prematch_df %>% mutate(.t = as.integer(diabetes_type2 == 1)), ".t", carrier_var),
    post$carrier, post$control, get_bal_smd(bal_label, "diabetes_type2"))
  r <- r + 1

  # Hypertension (optional)
  if ("hypertension" %in% names(matched_df)) {
    htn_pre  <- prematch_df %>% mutate(hypertension = factor(hypertension, levels = c(1, 0)))
    htn_post <- matched_df  %>% mutate(hypertension = factor(hypertension, levels = c(1, 0)))
    pre  <- t1_stats(htn_pre,  "hypertension", weighted = FALSE, group_var = carrier_var)
    post <- t1_stats(htn_post, "hypertension", group_var = carrier_var)
    rows[[r]] <- make_row_t1("  Hypertension, n (%)",
      pre$carrier, pre$control,
      t1_smd_inline(prematch_df %>% mutate(.h = as.integer(hypertension == 1)), ".h", carrier_var),
      post$carrier, post$control, get_bal_smd(bal_label, "hypertension"))
    r <- r + 1
  }

  rows[[r]] <- header_t1("Treatment Characteristics"); r <- r + 1

  smd_drug_pre  <- t1_smd_inline(prematch_df %>% mutate(.d = as.integer(drug == "semaglutide")), ".d", carrier_var)
  smd_drug_post <- get_bal_smd(bal_label, "drug")

  for (drug_name in c("semaglutide", "tirzepatide")) {
    label_drug <- if (drug_name == "semaglutide") "  Semaglutide, n (%)" else "  Tirzepatide, n (%)"
    label_dose <- if (drug_name == "semaglutide") "    \u22651.7 mg, n (%)" else "    \u226510 mg, n (%)"

    c_n_pre_d  <- sum(prematch_df[[carrier_var]] == 1 & prematch_df$drug == drug_name, na.rm = TRUE)
    k_n_pre_d  <- sum(prematch_df[[carrier_var]] == 0 & prematch_df$drug == drug_name, na.rm = TRUE)
    c_n_post_d <- sum(matched_df[[carrier_var]]  == 1 & matched_df$drug  == drug_name, na.rm = TRUE)
    k_n_post_d <- sum(matched_df[[carrier_var]]  == 0 & matched_df$drug  == drug_name, na.rm = TRUE)
    w_k_d <- sum(matched_df$weights_att[matched_df[[carrier_var]] == 0 &
                   matched_df$drug == drug_name], na.rm = TRUE)

    rows[[r]] <- make_row_t1(label_drug,
      sprintf("%d (%.1f)", c_n_pre_d,  100 * c_n_pre_d  / max(n_c_pre, 1)),
      sprintf("%d (%.1f)", k_n_pre_d,  100 * k_n_pre_d  / max(n_k_pre, 1)),
      smd_drug_pre,
      sprintf("%d (%.1f)", c_n_post_d, 100 * c_n_post_d / max(n_c_post, 1)),
      sprintf("%d (%.1f)", k_n_post_d, 100 * w_k_d / max(w_k_tot, 1)),
      smd_drug_post)
    r <- r + 1

    # High dose (dose_category variable — treat highest category as "high")
    if ("dose_category" %in% names(matched_df)) {
      dose_threshold <- if (drug_name == "semaglutide") "high" else "high"
      pre_drug  <- prematch_df[prematch_df$drug == drug_name, ]
      post_drug <- matched_df[matched_df$drug   == drug_name, ]
      if (nrow(post_drug) > 0 && "dose_category" %in% names(post_drug)) {
        high_levels <- grep("high|2\\.4|10mg|≥", unique(post_drug$dose_category),
                            ignore.case = TRUE, value = TRUE)
        if (length(high_levels) > 0) {
          c_hd_pre  <- sum(pre_drug[[carrier_var]]  == 1 & pre_drug$dose_category  %in% high_levels, na.rm = TRUE)
          k_hd_pre  <- sum(pre_drug[[carrier_var]]  == 0 & pre_drug$dose_category  %in% high_levels, na.rm = TRUE)
          n_c_pre_d_n <- sum(pre_drug[[carrier_var]] == 1, na.rm = TRUE)
          n_k_pre_d_n <- sum(pre_drug[[carrier_var]] == 0, na.rm = TRUE)
          c_hd_post <- sum(post_drug[[carrier_var]] == 1 & post_drug$dose_category %in% high_levels, na.rm = TRUE)
          k_hd_post <- sum(post_drug[[carrier_var]] == 0 & post_drug$dose_category %in% high_levels, na.rm = TRUE)
          rows[[r]] <- make_row_t1(label_dose,
            sprintf("%d (%.1f)", c_hd_pre, 100 * c_hd_pre / max(n_c_pre_d_n, 1)),
            sprintf("%d (%.1f)", k_hd_pre, 100 * k_hd_pre / max(n_k_pre_d_n, 1)),
            "",
            sprintf("%d (%.1f)", c_hd_post, 100 * c_hd_post / max(sum(post_drug[[carrier_var]] == 1, na.rm = TRUE), 1)),
            sprintf("%d (%.1f)", k_hd_post, 100 * k_hd_post / max(sum(post_drug[[carrier_var]] == 0, na.rm = TRUE), 1)),
            "")
          r <- r + 1
        }
      }
    }

    # Prior GLP-1 RA (combined prior_sema_tirz | prior_other_glp1)
    if (all(c("prior_sema_tirz", "prior_other_glp1") %in% names(matched_df))) {
      pre_drug  <- prematch_df %>% filter(drug == drug_name) %>%
        mutate(.pg = as.integer(prior_sema_tirz == 1 | prior_other_glp1 == 1))
      post_drug <- matched_df  %>% filter(drug == drug_name) %>%
        mutate(.pg = as.integer(prior_sema_tirz == 1 | prior_other_glp1 == 1))
      if (nrow(post_drug) > 0) {
        pg_pre  <- t1_stats(pre_drug  %>% mutate(.pg = factor(.pg, levels = c(1,0))), ".pg", weighted = FALSE, group_var = carrier_var)
        pg_post <- t1_stats(post_drug %>% mutate(.pg = factor(.pg, levels = c(1,0))), ".pg", group_var = carrier_var)
        rows[[r]] <- make_row_t1("    Prior GLP-1 RA use, n (%)",
          pg_pre$carrier, pg_pre$control,
          t1_smd_inline(pre_drug, ".pg", carrier_var),
          pg_post$carrier, pg_post$control,
          t1_smd_inline(post_drug, ".pg", carrier_var, weighted = TRUE))
        r <- r + 1
      }
    }
  }

  # Other anti-obesity medication (optional)
  if ("other_anti_obesity_med_baseline" %in% names(matched_df)) {
    aom_pre  <- prematch_df %>% mutate(other_anti_obesity_med_baseline = factor(other_anti_obesity_med_baseline, levels = c(1, 0)))
    aom_post <- matched_df  %>% mutate(other_anti_obesity_med_baseline = factor(other_anti_obesity_med_baseline, levels = c(1, 0)))
    pre  <- t1_stats(aom_pre,  "other_anti_obesity_med_baseline", weighted = FALSE, group_var = carrier_var)
    post <- t1_stats(aom_post, "other_anti_obesity_med_baseline", group_var = carrier_var)
    rows[[r]] <- make_row_t1("  Other anti-obesity medication, n (%)",
      pre$carrier, pre$control, "",
      post$carrier, post$control, "")
    r <- r + 1
  }

  # Follow-up duration (months)
  prematch_df2 <- prematch_df %>% mutate(.fu_mo = followup_duration / 30.44)
  matched_df2  <- matched_df  %>% mutate(.fu_mo = followup_duration / 30.44)
  pre  <- t1_stats(prematch_df2, ".fu_mo", weighted = FALSE, group_var = carrier_var)
  post <- t1_stats(matched_df2,  ".fu_mo", group_var = carrier_var)
  rows[[r]] <- make_row_t1("  Follow-up duration, months",
    pre$carrier, pre$control, t1_smd_inline(prematch_df2, ".fu_mo", carrier_var),
    post$carrier, post$control, get_bal_smd(bal_label, "followup_duration"))

  bind_rows(rows)
}

# Pre-match pools (carriers + no-variant controls)
no_variant <- analysis_overall %>%
  filter(any_glp1r_variant == 0 & carrier_gipr_primary == 0)

prematch_glp1r <- bind_rows(
  analysis_overall %>% filter(carrier_primary == 1),
  no_variant
)
prematch_gipr <- bind_rows(
  analysis_overall %>% filter(carrier_gipr_primary == 1),
  no_variant
)

table1_glp1r <- build_table1(prematch_glp1r, matched_glp1r,
                              "carrier_primary",     "GLP1R overall", "GLP1R")
table1_gipr  <- build_table1(prematch_gipr,  matched_gipr,
                              "carrier_gipr_primary", "GIPR overall",  "GIPR")

write_csv(table1_glp1r, file.path(fig_dir, "table1_glp1r.csv"))
write_csv(table1_gipr,  file.path(fig_dir, "table1_gipr.csv"))
cat("Saved: table1_glp1r.csv\n")
cat("Saved: table1_gipr.csv\n")
cat("\nGLP1R Table 1:\n"); print(table1_glp1r, n = Inf, width = 120)
cat("\nGIPR Table 1:\n");  print(table1_gipr,  n = Inf, width = 120)


###############################################################################
# SUPPLEMENTARY TABLE — GLP1R VARIANTS
#
# One row per unique variant among matched GLP1R primary carriers.
# Reads the raw carrier TSV (from 01_variant_classification.py) and filters
# to individuals who appear as carriers in the matched dataset.
###############################################################################

make_variant_consequence <- function(consequence) {
  case_when(
    consequence == "missense_variant"       ~ "Missense",
    consequence == "frameshift_variant"     ~ "Frameshift",
    consequence == "inframe_deletion"       ~ "Inframe deletion",
    consequence == "inframe_insertion"      ~ "Inframe insertion",
    consequence == "stop_gained"            ~ "Nonsense",
    consequence == "stop_lost"              ~ "Stop lost",
    consequence == "start_lost"             ~ "Start lost",
    consequence == "splice_donor_variant"   ~ "Splice donor",
    consequence == "splice_acceptor_variant" ~ "Splice acceptor",
    TRUE                                    ~ consequence
  )
}

# Load raw GLP1R carrier TSV and append rs146868158
glp1r_raw <- tryCatch({
  main <- read_tsv(PATHS$glp1r_carriers, show_col_types = FALSE) %>%
    rename(person_source_value = d_id)
  rs146 <- read_tsv(PATHS$rs146868158_carriers, show_col_types = FALSE) %>%
    rename(person_source_value = d_id) %>%
    filter(variant_id == PARAMS$rs146868158_id)
  bind_rows(main, rs146)
}, error = function(e) {
  cat("GLP1R carrier TSV not found; skipping supplementary variant tables.\n")
  NULL
})

if (!is.null(glp1r_raw)) {
  glp1r_carrier_ids <- matched_glp1r %>%
    filter(carrier_primary == 1) %>%
    pull(person_source_value)

  supp_glp1r <- glp1r_raw %>%
    filter(person_source_value %in% glp1r_carrier_ids) %>%
    group_by(variant_id) %>%
    summarise(
      rsID                = if ("rsid" %in% names(.)) first(rsid) else NA_character_,
      Mutation_Type       = first(MANE_CT_consequence),
      Protein_consequence = first(MANE_CT_HGVSP_custom),
      REVEL               = first(REVEL),
      AlphaMissense_Score = first(MANE_CT_am_pathogenicity),
      N_Carriers          = n_distinct(person_source_value),
      .groups = "drop"
    ) %>%
    mutate(
      Consequence   = make_variant_consequence(Mutation_Type),
      Protein_change = str_remove(Protein_consequence, "^p\\."),
      is_lof        = Consequence %in% c("Frameshift", "Nonsense", "Stop lost",
                                         "Start lost", "Splice donor", "Splice acceptor"),
      REVEL_safe    = replace_na(REVEL, 0),
      AM_safe       = replace_na(AlphaMissense_Score, 0),
      Variant_class = case_when(
        is_lof                                        ~ "pLoF",
        Consequence == "Missense" &
          (AM_safe >= PARAMS$am_damaging_threshold |
             REVEL_safe >= PARAMS$revel_damaging_threshold) ~ "Damaging missense",
        variant_id == PARAMS$rs146868158_id           ~ "Functionally validated (rs146868158)",
        Consequence == "Missense" &
          (AM_safe >= PARAMS$am_uncertain_lower |
             REVEL_safe >= PARAMS$revel_uncertain_lower) ~ "Uncertain missense",
        TRUE                                          ~ "Other"
      ),
      Functionally_validated = if_else(variant_id == PARAMS$rs146868158_id, "Yes", "No"),
      REVEL_fmt  = if_else(is.na(REVEL) | Consequence != "Missense",
                           "\u2014", sprintf("%.3f", REVEL)),
      AM_fmt     = if_else(is.na(AlphaMissense_Score) | Consequence != "Missense",
                           "\u2014", sprintf("%.3f", AlphaMissense_Score))
    ) %>%
    mutate(Variant_class = factor(Variant_class,
                                  levels = c("pLoF", "Damaging missense",
                                             "Functionally validated (rs146868158)",
                                             "Uncertain missense", "Other"))) %>%
    arrange(Variant_class, variant_id) %>%
    select(
      `Variant ID`           = variant_id,
      rsID,
      Consequence,
      `Protein change`       = Protein_change,
      `Variant class`        = Variant_class,
      `REVEL score`          = REVEL_fmt,
      `AlphaMissense score`  = AM_fmt,
      `Functionally validated` = Functionally_validated,
      `Carriers (n)`         = N_Carriers
    )

  write_tsv(supp_glp1r, file.path(fig_dir, "supplementary_table_glp1r_variants.tsv"))
  cat(sprintf("Saved: supplementary_table_glp1r_variants.tsv (%d variants)\n",
              nrow(supp_glp1r)))

  # --- SUPPLEMENTARY TABLE — GIPR VARIANTS ---
  # Include primary carriers (matched_gipr) and benign carriers (matched_gipr_benign)

  gipr_raw <- tryCatch(
    read_tsv(PATHS$gipr_carriers, show_col_types = FALSE) %>%
      rename(person_source_value = d_id),
    error = function(e) NULL
  )

  if (!is.null(gipr_raw)) {
    gipr_carrier_ids <- matched_gipr %>%
      filter(carrier_gipr_primary == 1) %>%
      pull(person_source_value)

    supp_gipr <- gipr_raw %>%
      filter(person_source_value %in% gipr_carrier_ids) %>%
      group_by(variant_id) %>%
      summarise(
        Mutation_Type       = first(MANE_CT_consequence),
        Protein_consequence = first(MANE_CT_HGVSP_custom),
        REVEL               = first(REVEL),
        AlphaMissense_Score = first(MANE_CT_am_pathogenicity),
        N_Carriers          = n_distinct(person_source_value),
        .groups = "drop"
      ) %>%
      mutate(
        Consequence    = make_variant_consequence(Mutation_Type),
        Protein_change = str_remove(Protein_consequence, "^p\\."),
        is_lof         = Consequence %in% c("Frameshift", "Nonsense", "Stop lost",
                                            "Start lost", "Splice donor", "Splice acceptor"),
        REVEL_safe     = replace_na(REVEL, 0),
        AM_safe        = replace_na(AlphaMissense_Score, 0),
        Variant_class  = case_when(
          is_lof                                          ~ "pLoF",
          Consequence == "Missense" &
            (AM_safe >= PARAMS$am_damaging_threshold |
               REVEL_safe >= PARAMS$revel_damaging_threshold) ~ "Damaging missense",
          Consequence == "Missense" &
            (AM_safe >= PARAMS$am_uncertain_lower |
               REVEL_safe >= PARAMS$revel_uncertain_lower)   ~ "Uncertain missense",
          Consequence == "Missense"                         ~ "Benign missense",
          TRUE                                              ~ "Other"
        ),
        REVEL_fmt = if_else(is.na(REVEL) | Consequence != "Missense",
                            "\u2014", sprintf("%.3f", REVEL)),
        AM_fmt    = if_else(is.na(AlphaMissense_Score) | Consequence != "Missense",
                            "\u2014", sprintf("%.3f", AlphaMissense_Score))
      ) %>%
      mutate(Variant_class = factor(Variant_class,
                                    levels = c("pLoF", "Damaging missense",
                                               "Uncertain missense", "Benign missense",
                                               "Other"))) %>%
      arrange(Variant_class, variant_id) %>%
      select(
        `Variant ID`          = variant_id,
        Consequence,
        `Protein change`      = Protein_change,
        `Variant class`       = Variant_class,
        `REVEL score`         = REVEL_fmt,
        `AlphaMissense score` = AM_fmt,
        `Carriers (n)`        = N_Carriers
      )

    write_tsv(supp_gipr, file.path(fig_dir, "supplementary_table_gipr_variants.tsv"))
    cat(sprintf("Saved: supplementary_table_gipr_variants.tsv (%d variants)\n",
                nrow(supp_gipr)))
  }
}


###############################################################################
# SUMMARY
###############################################################################

cat(sprintf("\nAll figures saved to %s\n", fig_dir))
list.files(fig_dir, pattern = "\\.(pdf|png|csv)$") %>%
  sort() %>%
  { cat(paste(" ", ., collapse = "\n"), "\n") }
